version: '3'
services:
  app:
    image: keinos/php8-jit
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    working_dir: /app
    command: php -S 0.0.0.0:9000 -t .
  composer:
    image: composer:1.10.8
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null